# Use an official Node.js runtime as a parent image
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Copy the app
COPY ./app /app

# Install dependencies
RUN npm install

# Expose port 8080 for the Vue app
EXPOSE 8080

# Run the Vue app
# this should be done with nginx / build..
CMD ["npm", "run", "serve"]